[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://bestcart-admin.netlify.com"
  to = "https://admin.bestcart.io"
  status = 301
  force = true

[[redirects]]
  from = "https://bestcart-admin-pre-production.netlify.com"
  to = "https://admin-pre-production.bestcart.io"
  status = 301
  force = true

[[redirects]]
  from = "https://bestcart-admin-staging.netlify.com"
  to = "https://admin-staging.bestcart.io"
  status = 301
  force = true


